### ISSUE TITLE
State range in API in wiki

### ISSUE THREAD

**Issue by flamendless** [chicogamedev/Luven#3]
Hi, may I request the addition of explicitly stating in the wiki the range of values for the `powerRange`, `speedRange` and `maxPower` for the flickering and flashing lights. It's kinda confusing to check if the range is in `0.0 - 1.0` or `0 to N`.

Thank you!

**Comment by halsten-dev** [comment]
Hi,

Actually their are stated as : { min = n, max = n } 

That means that their are neither a "0 to n" range because you could put : { min = 0.4, max = 0.94 } for example. 

The colors are indeed a range of 0 to 1, just like LÖVE.

So should I put something like : "n = 0 to n" ? 

I didn't put any range limit to those value to leave total freedom to the user. Even luven.newNumberRange(minN, maxN) does not speak about any limitations.

Please give me a bit more details on how I can help you, I'll be pleased to improve the Luven's wiki.

Thanks to you.

**Comment by flamendless** [comment]
In the example it is 0.4 and 0.94, but the api allows 0 to n which is kinda confusing for me as how does the value affect the light source? Maybe just a little more explanation would do?

**Comment by halsten-dev** [comment]
Ok I think I have understood. 

Actually, it requires to try'n'retry to find the good and desired result. 

So actually the power is a multiplier on the size of the light. You can see this in the drawLights() function. 

`lgDraw(light.shape.sprite, light.x, light.y, light.angle, light.scaleX * light.power, light.scaleY * light.power, light.shape.originX, light.shape.originY)` 

So indeed I could write something like : Value between 0 and 1 recommended, but this doesn't mean a value of 2 is impossible.

What do you think of that ?

**Comment by flamendless** [comment]
Yeah it should be noted that "power" is a multiplier for the scale of the image. So a power of 2 is too big.

At first i was setting power to 128, i thought there was problem with my code because i cant see any shadow (because the light covered the whole screen) haha.

**Comment by flamendless** [comment]
Also, there's no example of flashing in main.lua. people would also want to see what that looks like in the demo gif

**Comment by halsten-dev** [comment]
Yeah I understand I will update the wiki.

I added the "z" shortcut to the main.lua to spawn a flashing light.

I will work on a better demo with a little game to show every aspect of Luven. screen shake fade in fade out and so on. 

I think it will be useful, and thanks for pointing it out !
